# took from https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml

name: QCS Build and Test (windows)

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ "!master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create build environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure
        working-directory: ${{github.workspace}}/build
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Collect binaries
        run: |
          mkdir -p binaries
          cp ${{github.workspace}}/build/qcs.exe binaries/
          cp ${{github.workspace}}/build/tests.exe binaries/

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: qcs-windows
          path: binaries/*
          if-no-files-found: error
          retention-days: 5

  test:
    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: qcs-windows
          path: binaries

      - working-directory: binaries
        run: ./tests.exe
